# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33e6680abc49aaf82fc69a08ff3bdfe4e4e67a0d2db0b859620a913914de72254c15a59d496143bfc2b181a268244bd595695685574848134b32ab3893dec9c9

test:
  secret_key_base: 3922cc104c456271325fcbfa43b5653e2554ab7ee2f9022d8cc05581bd2224ea6d46fc77f53e9f545139bfe74269d2c8e5dd83411042aa6fc0c0bf9360512f62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
